Add new owner @zzxwill
crossplane/provider-alibaba pull request #94
Opened 2021-07-13 00:59 UTC by zzxwill

### Description of your changes

Added a new owner @zzxwill and remove some from Alibaba cloud

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

[contribution process]: https://git.io/fj2m9

2021-07-13 01:50 UTC, hongchaodeng approved these changes
LGTM

2021-07-13 05:06 UTC, wonderflow commented on OWNERS.md
> -* Sun Jianbo <wonderflow@icloud.com> ([wonderflow](https://github.com/wonderflow))
why remove me?

2021-07-13 05:09 UTC, hongchaodeng requested changes
Don't remove existing owner except Ryan.

2021-07-13 06:33 UTC, wonderflow approved these changes

2021-07-13 06:42 UTC, resouer approved these changes
LGTM

2021-07-14 04:28 UTC, jbw976 commented
Is it clear what changes we want to make here in this PR? @hongchaodeng mentioned this earlier:

> Don't remove existing owner except Ryan.

But there were approvals after that even though others besides Ryan are being removed.  Let's make sure there's agreement for these changes since they impact maintainer status.

2021-07-14 06:22 UTC, zzxwill commented
@jbw976 We'd like to clean up inactive owners from this repo. We discussed the change and maintainers bending removed have approved the change.

2021-07-14 09:01 UTC, hongchaodeng approved these changes
lgtm

2021-07-14 09:04 UTC, hongchaodeng commented
Hi @jbw976 .

Sorry for the confusion. We are out of sync initially due to text message lost in disconnection... But we can synced up again on the change.

For more context, Ryan has left our team and we also shift people's focus on different projects. This is our latest roster to maintain the project.

As for @zzxwill , he has contributed a significant percentage of code to this repo. He is definitely qualified to be the owner :)

Feel free to ask questions if you still have any concerns.

2021-07-14 14:36 UTC, jbw976 approved these changes
Great everyone, thank you for the further insight.  I have no problems at all with adding @zzxwill, I just wanted to make sure that no one was being removed that shouldn't be.  LGTM! 🙇‍♂️

2021-07-14 14:36 UTC, merged

2021-07-14 14:40 UTC, jbw976 commented
@zzxwill can you follow these steps to become a member of the Crossplane org, so that I can follow up to add you with maintainer access to this repo?
https://github.com/crossplane/org/blob/main/processes/new-member.md

I am happy to sponsor you and I'm sure @hongchaodeng is as well :)